spring.application.name=springjwt
logging.level.root=ERROR
logging.level.org.springframework.boot.tomcat=INFO
logging.level.org.springframework.boot.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
jwt.secret=68eb25875a686cc2ace86cc46e98deac660f153e7fc504021613d8c6714f41ae